import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TEKMBILICAL SOLUTIONS PRIVATE LIMITED",
  description: "Generated by TEKMBILICAL SOLUTIONS PRIVATE LIMITED",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
